[package]
name = "exact-cover"
version = "0.1.0"
authors = ["queuedq <queuedq@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.13"
indexmap = "1.6.2"
